program: model/multiple_high_level_model/train_wandb.py
method: bayes # Use Bayesian optimization to find best params faster than random
metric:
  name: val_mse
  goal: minimize
parameters:
  learning_rate:
    values: [0.001, 0.0003, 0.0001]
  weight_decay:
    values: [0.0001, 0.00001, 0.0]
  # obs_max:
  #   values: [10, 20, 40]
  obs_max:
    values: [10, 40]
  # dropout:
  #   values: [0.0, 0.05, 0.1]
  dropout:
    values: [0.0]
  # batch_size:
  #   value: [1, 8, 16]
  batch_size:
    value: [1]
  epochs:
    value: 60001